#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
  if [[ $(pidof "${_prs}") ]]; then
    killall -9 "${_prs}"
  fi
done

# Polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
  /usr/lib/xfce-polkit/xfce-polkit &
fi

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &

# Set wallpaper (move this to the end)
sleep 5 && hyprpaper &
# echo "Executing wallpaper script with argument: ~/.config/hypr/wallpapers/wallpaper.png" >> /tmp/wallpaper.log
# WALLPAPER="$HOME/.config/hypr/wallpapers/wallpaper.png"
# ~/.config/hypr/scripts/wallpaper "$WALLPAPER" &
