# preload = /home/rolf/Design/Wallpapers/HyprlandWallpapers/Wallpaper-Bank-main/wallpapers/Dark_Nature.png
# wallpaper = eDP-1,/home/rolf/.config/hypr/wallpapers/wallpaper.png

# preload = /home/rolf/.config/hypr/wallpapers/wallpaper.png
# wallpaper = DP-3,/home/rolf/.config/hypr/wallpapers/wallpaper.png

# preload = /home/rolf/.config/hypr/wallpapers/wallpaper.png
# wallpaper = eDP-1, /home/rolf/.config/hypr/wallpapers/wallpaper.png


# Hyprpaper Configuration File

# Preload wallpapers to improve performance
preload = /home/rolf/.config/hypr/wallpapers/wallpaper.png
preload = /home/rolf/.config/hypr/wallpapers/wallpaper-alt.png

# Wallpaper rules
# 1. eDP-1 (Laptop Display)
wallpaper = eDP-1,/home/rolf/.config/hypr/wallpapers/wallpaper.png

# 2. HDMI-A-1 (External Monitor)
# 2. DP-1 (External Monitor)
wallpaper = DP-1,/home/rolf/.config/hypr/wallpapers/wallpaper-alt.png

# wallpaper = HDMI-A-1,/home/rolf/.config/hypr/wallpapers/wallpaper-alt.png

ipc = on
splash = false
preload = /home/rolf/.config/hypr/wallpapers/wallpaper.png
preload = /home/rolf/.config/hypr/wallpapers/wallpaper-alt.png
wallpaper = eDP-1,/home/rolf/.config/hypr/wallpapers/wallpaper.png
wallpaper = DP-1,/home/rolf/.config/hypr/wallpapers/wallpaper-alt.png
