exec-once = vicinae server
bind = SUPER CTRL, D, exec, vicinae toggle

# 1. Use 'ignorezero' instead of 'ignorealpha'
# 2. Ensure syntax is explicitly 'rule, namespacename'
layerrule = blur, vicinae
layerrule = ignorezero, vicinae
layerrule = noanim, vicinae

# exec-once = vicinae server

# bind = SUPER CTRL, D, exec, vicinae toggle
#
# layerrule = blur, vicinae
# layerrule = ignorezero, vicinae
# layerrule = noanim, vicinae
# }
